// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

namespace Clione___Trickster_Online_XML_Editor
{
    partial class MainForm
    {
        /// <summary>
        ///  Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        #region Windows Form Designer generated code

        private System.Windows.Forms.MenuStrip menuStrip1;
        private System.Windows.Forms.ToolStripMenuItem tlstrpOpenFolder;
        private System.Windows.Forms.ToolStripMenuItem saveToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem aboutToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem preferencesToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem aboutToolStripMenuItem1;
        private System.Windows.Forms.Timer fadeTimer;

        /// <summary>
        ///  Required method for Designer support - do not modify
        ///  the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(MainForm));
            menuStrip1 = new MenuStrip();
            tlstrpOpenFolder = new ToolStripMenuItem();
            saveToolStripMenuItem = new ToolStripMenuItem();
            cloneRowToolStripMenuItem = new ToolStripMenuItem();
            editColumnsToolStripMenuItem = new ToolStripMenuItem();
            createTableToolStripMenuItem = new ToolStripMenuItem();
            deleteTableToolStripMenuItem = new ToolStripMenuItem();
            aboutToolStripMenuItem = new ToolStripMenuItem();
            preferencesToolStripMenuItem = new ToolStripMenuItem();
            aboutToolStripMenuItem1 = new ToolStripMenuItem();
            logToolStripMenuItem = new ToolStripMenuItem();
            fadeTimer = new System.Windows.Forms.Timer(components);
            lstXML = new ListBox();
            splitContainer1 = new SplitContainer();
            txtbxSearchFiles = new TextBox();
            txtbxSearchTable = new TextBox();
            lblCurrentTable = new Label();
            dtgrdvwXML = new DataGridView();
            statusStrip1 = new StatusStrip();
            tlstrpSave = new ToolStripStatusLabel();
            toolStripStatusLabel1 = new ToolStripStatusLabel();
            tlstrpStatus = new ToolStripStatusLabel();
            toolStripStatusLabel2 = new ToolStripStatusLabel();
            tlstrpXMLCount = new ToolStripStatusLabel();
            toolStripStatusLabel3 = new ToolStripStatusLabel();
            tlstrpRowCount = new ToolStripStatusLabel();
            toolStripStatusLabel4 = new ToolStripStatusLabel();
            tlstrplblSearch = new ToolStripStatusLabel();
            ctxMenuXMLList = new ContextMenuStrip(components);
            tlstrpmnTableName = new ToolStripMenuItem();
            toolStripSeparator1 = new ToolStripSeparator();
            renameToolStripMenuItem = new ToolStripMenuItem();
            deleteToolStripMenuItem = new ToolStripMenuItem();
            showInExplorerToolStripMenuItem = new ToolStripMenuItem();
            menuStrip1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)splitContainer1).BeginInit();
            splitContainer1.Panel1.SuspendLayout();
            splitContainer1.Panel2.SuspendLayout();
            splitContainer1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)dtgrdvwXML).BeginInit();
            statusStrip1.SuspendLayout();
            ctxMenuXMLList.SuspendLayout();
            SuspendLayout();
            // 
            // menuStrip1
            // 
            menuStrip1.BackColor = Color.Gainsboro;
            menuStrip1.Font = new Font("Segoe UI", 9F, FontStyle.Bold, GraphicsUnit.Point, 0);
            menuStrip1.Items.AddRange(new ToolStripItem[] { tlstrpOpenFolder, saveToolStripMenuItem, cloneRowToolStripMenuItem, editColumnsToolStripMenuItem, createTableToolStripMenuItem, deleteTableToolStripMenuItem, aboutToolStripMenuItem, logToolStripMenuItem });
            menuStrip1.Location = new Point(0, 0);
            menuStrip1.Name = "menuStrip1";
            menuStrip1.Padding = new Padding(7, 2, 0, 2);
            menuStrip1.Size = new Size(963, 24);
            menuStrip1.TabIndex = 0;
            menuStrip1.Text = "menuStrip1";
            // 
            // tlstrpOpenFolder
            // 
            tlstrpOpenFolder.ForeColor = Color.Maroon;
            tlstrpOpenFolder.Name = "tlstrpOpenFolder";
            tlstrpOpenFolder.Size = new Size(49, 20);
            tlstrpOpenFolder.Text = "Open";
            tlstrpOpenFolder.Click += tlstrpOpenFolder_Click;
            // 
            // saveToolStripMenuItem
            // 
            saveToolStripMenuItem.ForeColor = Color.FromArgb(128, 64, 0);
            saveToolStripMenuItem.Name = "saveToolStripMenuItem";
            saveToolStripMenuItem.Size = new Size(46, 20);
            saveToolStripMenuItem.Text = "Save";
            saveToolStripMenuItem.Click += saveToolStripMenuItem_Click;
            // 
            // cloneRowToolStripMenuItem
            // 
            cloneRowToolStripMenuItem.ForeColor = Color.Olive;
            cloneRowToolStripMenuItem.Name = "cloneRowToolStripMenuItem";
            cloneRowToolStripMenuItem.Size = new Size(78, 20);
            cloneRowToolStripMenuItem.Text = "Clone Row";
            cloneRowToolStripMenuItem.Click += cloneRowToolStripMenuItem_Click;
            // 
            // editColumnsToolStripMenuItem
            // 
            editColumnsToolStripMenuItem.ForeColor = Color.Green;
            editColumnsToolStripMenuItem.Name = "editColumnsToolStripMenuItem";
            editColumnsToolStripMenuItem.Size = new Size(90, 20);
            editColumnsToolStripMenuItem.Text = "Edit Columns";
            editColumnsToolStripMenuItem.Click += editColumnsToolStripMenuItem_Click;
            // 
            // createTableToolStripMenuItem
            // 
            createTableToolStripMenuItem.ForeColor = Color.Teal;
            createTableToolStripMenuItem.Name = "createTableToolStripMenuItem";
            createTableToolStripMenuItem.Size = new Size(88, 20);
            createTableToolStripMenuItem.Text = "Create Table";
            createTableToolStripMenuItem.Click += createTableToolStripMenuItem_Click;
            // 
            // deleteTableToolStripMenuItem
            // 
            deleteTableToolStripMenuItem.ForeColor = Color.Navy;
            deleteTableToolStripMenuItem.Name = "deleteTableToolStripMenuItem";
            deleteTableToolStripMenuItem.Size = new Size(89, 20);
            deleteTableToolStripMenuItem.Text = "Delete Table";
            deleteTableToolStripMenuItem.Click += deleteTableToolStripMenuItem_Click;
            // 
            // aboutToolStripMenuItem
            // 
            aboutToolStripMenuItem.DropDownItems.AddRange(new ToolStripItem[] { preferencesToolStripMenuItem, aboutToolStripMenuItem1 });
            aboutToolStripMenuItem.ForeColor = Color.Purple;
            aboutToolStripMenuItem.Name = "aboutToolStripMenuItem";
            aboutToolStripMenuItem.Size = new Size(65, 20);
            aboutToolStripMenuItem.Text = "Settings";
            // 
            // preferencesToolStripMenuItem
            // 
            preferencesToolStripMenuItem.Enabled = false;
            preferencesToolStripMenuItem.Name = "preferencesToolStripMenuItem";
            preferencesToolStripMenuItem.Size = new Size(142, 22);
            preferencesToolStripMenuItem.Text = "Preferences";
            // 
            // aboutToolStripMenuItem1
            // 
            aboutToolStripMenuItem1.Name = "aboutToolStripMenuItem1";
            aboutToolStripMenuItem1.Size = new Size(142, 22);
            aboutToolStripMenuItem1.Text = "About";
            aboutToolStripMenuItem1.Click += aboutToolStripMenuItem1_Click;
            // 
            // logToolStripMenuItem
            // 
            logToolStripMenuItem.ForeColor = Color.Maroon;
            logToolStripMenuItem.Name = "logToolStripMenuItem";
            logToolStripMenuItem.Size = new Size(39, 20);
            logToolStripMenuItem.Text = "Log";
            logToolStripMenuItem.Click += logToolStripMenuItem_Click;
            // 
            // fadeTimer
            // 
            fadeTimer.Enabled = true;
            fadeTimer.Interval = 15;
            fadeTimer.Tick += FadeTimer_Tick;
            // 
            // lstXML
            // 
            lstXML.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
            lstXML.BackColor = Color.FromArgb(64, 64, 64);
            lstXML.BorderStyle = BorderStyle.FixedSingle;
            lstXML.Font = new Font("Segoe UI", 9.75F, FontStyle.Regular, GraphicsUnit.Point, 0);
            lstXML.ForeColor = Color.Honeydew;
            lstXML.FormattingEnabled = true;
            lstXML.ItemHeight = 17;
            lstXML.Location = new Point(3, 43);
            lstXML.Name = "lstXML";
            lstXML.Size = new Size(197, 512);
            lstXML.TabIndex = 1;
            lstXML.SelectedIndexChanged += lstXML_SelectedIndexChanged;
            lstXML.MouseDown += lstXML_MouseDown;
            // 
            // splitContainer1
            // 
            splitContainer1.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
            splitContainer1.BackColor = Color.Transparent;
            splitContainer1.Font = new Font("Segoe UI", 11.25F, FontStyle.Regular, GraphicsUnit.Point, 0);
            splitContainer1.Location = new Point(12, 27);
            splitContainer1.Name = "splitContainer1";
            // 
            // splitContainer1.Panel1
            // 
            splitContainer1.Panel1.Controls.Add(txtbxSearchFiles);
            splitContainer1.Panel1.Controls.Add(lstXML);
            // 
            // splitContainer1.Panel2
            // 
            splitContainer1.Panel2.Controls.Add(txtbxSearchTable);
            splitContainer1.Panel2.Controls.Add(lblCurrentTable);
            splitContainer1.Panel2.Controls.Add(dtgrdvwXML);
            splitContainer1.Size = new Size(939, 567);
            splitContainer1.SplitterDistance = 203;
            splitContainer1.TabIndex = 2;
            // 
            // txtbxSearchFiles
            // 
            txtbxSearchFiles.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
            txtbxSearchFiles.BackColor = Color.Gainsboro;
            txtbxSearchFiles.Location = new Point(3, 8);
            txtbxSearchFiles.MaxLength = 250;
            txtbxSearchFiles.Name = "txtbxSearchFiles";
            txtbxSearchFiles.Size = new Size(197, 27);
            txtbxSearchFiles.TabIndex = 2;
            txtbxSearchFiles.TextChanged += txtbxSearchFiles_TextChanged;
            // 
            // txtbxSearchTable
            // 
            txtbxSearchTable.Anchor = AnchorStyles.Top | AnchorStyles.Right;
            txtbxSearchTable.BackColor = Color.Gainsboro;
            txtbxSearchTable.Location = new Point(564, 8);
            txtbxSearchTable.MaxLength = 250;
            txtbxSearchTable.Name = "txtbxSearchTable";
            txtbxSearchTable.Size = new Size(165, 27);
            txtbxSearchTable.TabIndex = 3;
            txtbxSearchTable.Enter += txtbxSearchTable_Enter;
            txtbxSearchTable.KeyDown += txtbxSearchTable_KeyDown;
            txtbxSearchTable.Leave += txtbxSearchTable_Leave;
            // 
            // lblCurrentTable
            // 
            lblCurrentTable.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
            lblCurrentTable.Font = new Font("Segoe UI", 12F, FontStyle.Bold, GraphicsUnit.Point, 0);
            lblCurrentTable.ForeColor = Color.FromArgb(128, 255, 255);
            lblCurrentTable.Location = new Point(3, 9);
            lblCurrentTable.Name = "lblCurrentTable";
            lblCurrentTable.Size = new Size(545, 20);
            lblCurrentTable.TabIndex = 1;
            lblCurrentTable.Text = "No Table Selected";
            lblCurrentTable.TextAlign = ContentAlignment.MiddleLeft;
            // 
            // dtgrdvwXML
            // 
            dtgrdvwXML.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
            dtgrdvwXML.BorderStyle = BorderStyle.Fixed3D;
            dtgrdvwXML.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            dtgrdvwXML.Location = new Point(3, 43);
            dtgrdvwXML.Name = "dtgrdvwXML";
            dtgrdvwXML.Size = new Size(726, 524);
            dtgrdvwXML.TabIndex = 0;
            // 
            // statusStrip1
            // 
            statusStrip1.BackColor = Color.Gainsboro;
            statusStrip1.Items.AddRange(new ToolStripItem[] { tlstrpSave, toolStripStatusLabel1, tlstrpStatus, toolStripStatusLabel2, tlstrpXMLCount, toolStripStatusLabel3, tlstrpRowCount, toolStripStatusLabel4, tlstrplblSearch });
            statusStrip1.Location = new Point(0, 597);
            statusStrip1.Name = "statusStrip1";
            statusStrip1.Size = new Size(963, 22);
            statusStrip1.TabIndex = 3;
            statusStrip1.Text = "statusStrip1";
            // 
            // tlstrpSave
            // 
            tlstrpSave.ForeColor = SystemColors.ActiveCaptionText;
            tlstrpSave.Name = "tlstrpSave";
            tlstrpSave.Size = new Size(0, 17);
            // 
            // toolStripStatusLabel1
            // 
            toolStripStatusLabel1.ForeColor = SystemColors.ActiveBorder;
            toolStripStatusLabel1.Name = "toolStripStatusLabel1";
            toolStripStatusLabel1.Size = new Size(10, 17);
            toolStripStatusLabel1.Text = "|";
            // 
            // tlstrpStatus
            // 
            tlstrpStatus.ForeColor = SystemColors.ActiveCaptionText;
            tlstrpStatus.Name = "tlstrpStatus";
            tlstrpStatus.Size = new Size(42, 17);
            tlstrpStatus.Text = "Ready.";
            // 
            // toolStripStatusLabel2
            // 
            toolStripStatusLabel2.ForeColor = SystemColors.ActiveBorder;
            toolStripStatusLabel2.Name = "toolStripStatusLabel2";
            toolStripStatusLabel2.Size = new Size(10, 17);
            toolStripStatusLabel2.Text = "|";
            // 
            // tlstrpXMLCount
            // 
            tlstrpXMLCount.ForeColor = SystemColors.ActiveCaptionText;
            tlstrpXMLCount.Name = "tlstrpXMLCount";
            tlstrpXMLCount.Size = new Size(124, 17);
            tlstrpXMLCount.Text = "Loaded XML Count : 0";
            // 
            // toolStripStatusLabel3
            // 
            toolStripStatusLabel3.ForeColor = SystemColors.ActiveBorder;
            toolStripStatusLabel3.Name = "toolStripStatusLabel3";
            toolStripStatusLabel3.Size = new Size(10, 17);
            toolStripStatusLabel3.Text = "|";
            // 
            // tlstrpRowCount
            // 
            tlstrpRowCount.ForeColor = SystemColors.ActiveCaptionText;
            tlstrpRowCount.Name = "tlstrpRowCount";
            tlstrpRowCount.Size = new Size(110, 17);
            tlstrpRowCount.Text = "Showing 0 / 0 Rows";
            // 
            // toolStripStatusLabel4
            // 
            toolStripStatusLabel4.ForeColor = SystemColors.ActiveBorder;
            toolStripStatusLabel4.Name = "toolStripStatusLabel4";
            toolStripStatusLabel4.Size = new Size(10, 17);
            toolStripStatusLabel4.Text = "|";
            // 
            // tlstrplblSearch
            // 
            tlstrplblSearch.ForeColor = SystemColors.ActiveCaptionText;
            tlstrplblSearch.Name = "tlstrplblSearch";
            tlstrplblSearch.Size = new Size(0, 17);
            // 
            // ctxMenuXMLList
            // 
            ctxMenuXMLList.BackColor = SystemColors.AppWorkspace;
            ctxMenuXMLList.Font = new Font("Segoe UI", 9.75F, FontStyle.Regular, GraphicsUnit.Point, 0);
            ctxMenuXMLList.Items.AddRange(new ToolStripItem[] { tlstrpmnTableName, toolStripSeparator1, renameToolStripMenuItem, deleteToolStripMenuItem, showInExplorerToolStripMenuItem });
            ctxMenuXMLList.Name = "contextMenuStrip1";
            ctxMenuXMLList.RenderMode = ToolStripRenderMode.Professional;
            ctxMenuXMLList.ShowImageMargin = false;
            ctxMenuXMLList.Size = new Size(162, 98);
            ctxMenuXMLList.Opening += ctxMenuXMLList_Opening;
            // 
            // tlstrpmnTableName
            // 
            tlstrpmnTableName.Enabled = false;
            tlstrpmnTableName.Name = "tlstrpmnTableName";
            tlstrpmnTableName.Size = new Size(161, 22);
            tlstrpmnTableName.Text = "No Table Selected!";
            // 
            // toolStripSeparator1
            // 
            toolStripSeparator1.Name = "toolStripSeparator1";
            toolStripSeparator1.Size = new Size(158, 6);
            // 
            // renameToolStripMenuItem
            // 
            renameToolStripMenuItem.Name = "renameToolStripMenuItem";
            renameToolStripMenuItem.Size = new Size(161, 22);
            renameToolStripMenuItem.Text = "Rename";
            renameToolStripMenuItem.Click += renameToolStripMenuItem_Click;
            // 
            // deleteToolStripMenuItem
            // 
            deleteToolStripMenuItem.Name = "deleteToolStripMenuItem";
            deleteToolStripMenuItem.Size = new Size(161, 22);
            deleteToolStripMenuItem.Text = "Delete";
            deleteToolStripMenuItem.Click += deleteToolStripMenuItem_Click;
            // 
            // showInExplorerToolStripMenuItem
            // 
            showInExplorerToolStripMenuItem.Name = "showInExplorerToolStripMenuItem";
            showInExplorerToolStripMenuItem.Size = new Size(161, 22);
            showInExplorerToolStripMenuItem.Text = "Show in Explorer";
            showInExplorerToolStripMenuItem.Click += showInExplorerToolStripMenuItem_Click;
            // 
            // MainForm
            // 
            AutoScaleDimensions = new SizeF(8F, 17F);
            AutoScaleMode = AutoScaleMode.Font;
            BackColor = Color.DimGray;
            ClientSize = new Size(963, 619);
            Controls.Add(statusStrip1);
            Controls.Add(splitContainer1);
            Controls.Add(menuStrip1);
            Font = new Font("Cascadia Code", 9.75F, FontStyle.Regular, GraphicsUnit.Point, 0);
            ForeColor = Color.MintCream;
            Icon = (Icon)resources.GetObject("$this.Icon");
            MainMenuStrip = menuStrip1;
            Name = "MainForm";
            Opacity = 0D;
            StartPosition = FormStartPosition.CenterScreen;
            Text = "Clione - Trickster Online XML Editor";
            Load += MainForm_Load;
            menuStrip1.ResumeLayout(false);
            menuStrip1.PerformLayout();
            splitContainer1.Panel1.ResumeLayout(false);
            splitContainer1.Panel1.PerformLayout();
            splitContainer1.Panel2.ResumeLayout(false);
            splitContainer1.Panel2.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)splitContainer1).EndInit();
            splitContainer1.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)dtgrdvwXML).EndInit();
            statusStrip1.ResumeLayout(false);
            statusStrip1.PerformLayout();
            ctxMenuXMLList.ResumeLayout(false);
            ResumeLayout(false);
            PerformLayout();
        }

        #endregion
        private SplitContainer splitContainer1;
        private DataGridView dtgrdvwXML;
        private Label lblCurrentTable;
        private TextBox txtbxSearchFiles;
        private TextBox txtbxSearchTable;
        private ToolStripMenuItem cloneRowToolStripMenuItem;
        private ToolStripMenuItem editColumnsToolStripMenuItem;
        private StatusStrip statusStrip1;
        private ToolStripStatusLabel tlstrpXMLCount;
        private ToolStripMenuItem createTableToolStripMenuItem;
        private ToolStripMenuItem deleteTableToolStripMenuItem;
        private ToolStripStatusLabel tlstrpStatus;
        private ToolStripStatusLabel toolStripStatusLabel2;
        private ToolStripStatusLabel toolStripStatusLabel3;
        private ToolStripStatusLabel tlstrpRowCount;
        private ToolStripStatusLabel toolStripStatusLabel4;
        private ToolStripStatusLabel tlstrpSave;
        private ToolStripStatusLabel toolStripStatusLabel1;
        private ToolStripMenuItem logToolStripMenuItem;
        private ContextMenuStrip ctxMenuXMLList;
        private ToolStripMenuItem renameToolStripMenuItem;
        private ToolStripMenuItem deleteToolStripMenuItem;
        private ToolStripMenuItem showInExplorerToolStripMenuItem;
        private ToolStripMenuItem tlstrpmnTableName;
        private ToolStripSeparator toolStripSeparator1;
        public ListBox lstXML;
        private ToolStripStatusLabel tlstrplblSearch;
    }
}
